In [1]:
import pandas as pd

In [11]:
data_filled = pd.read_csv('../raw/CRMLSSold202404_filled.csv')
data_filled.head()

C:\Users\Tangent\AppData\Local\Temp\ipykernel_35464\1729651822.py:1: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  data_filled = pd.read_csv('../raw/CRMLSSold202404_filled.csv')

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,NaN,True,NaN,NaN,NaN,159000.0,555125771,deborah.potestio@c21selectgroup.com,2024-04-29,45000.0,...,NaN,False,NaN,NaN,95916,0.0,336283.2,NaN,False,False
1,NaN,True,NaN,NaN,NaN,144000.0,554271746,crchapman@sbcglobal.net,2024-04-26,78000.0,...,NaN,False,NaN,NaN,95966,0.0,101495.0,NaN,False,False
2,NaN,True,NaN,NaN,False,265000.0,543251400,michaelg@londonproperties.com,2024-04-02,250000.0,...,3.0,False,2.0,Fresno Unified,93726,0.0,8100.0,NaN,False,False
3,NaN,True,NaN,NaN,NaN,925000.0,539236677,chris.campbell@msn.com,2024-04-10,815000.0,...,NaN,False,NaN,NaN,92223,0.0,564988.0,NaN,False,False
4,NaN,True,NaN,NaN,NaN,25000.0,538449222,rrinder@sbcglobal.net,2024-04-06,15000.0,...,NaN,False,NaN,NaN,95966,0.0,6098.0,NaN,False,False

In [13]:
data = pd.read_csv('../raw/CRMLSSold202410.csv')
data.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,OrangeCounty,OrangeCounty,NaN,False,NaN,NaN,NaN,6229080.00,544379760,fmandegari@gmail.com,...,NaN,55626.0,NaN,False,NaN,NaN,92683,0.0,55626.0,NaN
1,InlandValleys,InlandValleys,NaN,True,NaN,NaN,False,239900.00,526120619,pacocraig26@gmail.com,...,NaN,217800.0,2.0,False,0.0,Morongo Unified,92256,0.0,217800.0,NaN
2,CitrusValley,CitrusValley,NaN,NaN,NaN,NaN,NaN,12820.85,509763705,lynny@mgrrealestate.com,...,NaN,129458.0,NaN,NaN,NaN,NaN,91764,NaN,129458.0,NaN
3,Malibu,Malibu,"Carpet,Wood",True,NaN,NaN,False,120000.00,447068498,pamela@vacationrentalmalibu.com,...,NaN,45683.0,NaN,False,NaN,NaN,90265,NaN,45683.0,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,4195.00,446147831,realtorashraf@gmail.com,...,NaN,NaN,NaN,NaN,3.0,NaN,93021,0.0,NaN,NaN

In [8]:
data_filled_2 = pd.read_csv('../raw/CRMLSSold202501_filled.csv')
data_filled_2.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,PasadenaFoothills,PasadenaFoothills,NaN,True,NaN,NaN,NaN,699000.0,538489291,jimo@bridgeadvisorsllc.com,...,NaN,False,NaN,NaN,90031,0.0,34350.0,NaN,False,False
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Carpet,Stone,Tile,Wood",True,NaN,True,True,45000.0,509724017,mwoods@marybethwoods.com,...,NaN,False,NaN,NaN,90402,NaN,5717.0,NaN,False,False
2,PalmSprings,PalmSprings,Tile,True,NaN,NaN,True,8500.0,498101084,encorepremiergroup@bdhomes.com,...,NaN,False,3.0,NaN,92270,1.0,4792.0,NaN,False,False
3,HighDesert,HighDesert,NaN,True,NaN,NaN,NaN,100000.0,446933645,billquimby.re@gmail.com,...,NaN,False,NaN,NaN,92307,NaN,217800.0,NaN,False,False
4,PalmSprings,PalmSprings,"Carpet,Tile",True,NaN,NaN,True,7500.0,441682993,encorepremiergroup@bdhomes.com,...,NaN,False,3.0,NaN,92270,1103.0,5227.0,NaN,False,False